apiVersion: application-networking.k8s.aws/v1alpha1
kind: TargetGroupPolicy
metadata:
  name: wsc2024-policy
  namespace: wsc2024
spec:
  targetRef:
    group: ""
    kind: Service
    name: customer-svc
  protocol: HTTP
  protocolVersion: HTTP1
  healthCheck:
    enabled: true
    intervalSeconds: 10
    timeoutSeconds: 1
    healthyThresholdCount: 3
    unhealthyThresholdCount: 2
    path: "/healthcheck"
    port: 8080
    protocol: HTTP
    protocolVersion: HTTP1
    statusMatch: "200"