apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-credentials
  namespace: wsc2024
spec:
  refreshInterval: 24m
  secretStoreRef:
    name: aws-secrets
    kind: SecretStore
  target:
    name: db-credentials
    creationPolicy: Owner
  data:
    - secretKey: MYSQL_USER
      remoteRef:
        key: wsc2024/secret
        property: username
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: wsc2024/secret
        property: password
    - secretKey: MYSQL_HOST
      remoteRef:
        key: wsc2024/secret
        property: host
    - secretKey: MYSQL_PORT
      remoteRef:
        key: wsc2024/secret
        property: port
    - secretKey: MYSQL_DBNAME
      remoteRef:
        key: wsc2024/secret
        property: dbname
    - secretKey: US_REGION
      remoteRef:
        key: wsc2024/secret
        property: aws_region